# Rockstar Newswire Configuration

# Enable or Disable Services
# Set to true or false to toggle functionality.
enableDiscord: true # Post updates to Discord via Webhook
enableRSS: true     # Generate RSS feed  (feed.xml)
mergeFeeds: true    # If true, all enabled genres are merged into one feed.xml. If false, separate feed-[genre].xml files are created.

# Discord Configuration
# You can also set this using the DISCORD_WEBHOOK_URL environment variable (recommended for Docker).
# If the environment variable is set, it will take precedence over this value.
webhookUrl: "https://discordapp.com/api/webhooks/1458124204263346289/gG-0gKWuzqyexcZD0qe4d6MKZ0vCE3W8dd63kpxFIe5Xmik8s6pXtscVHqO20F6UohvF"

# Discord Bot Profile
discordProfileName: "Rockstar Newswire Tracker"
discordAvatarUrl: "https://yt3.googleusercontent.com/-jCZaDR8AoEgC6CBPWFubF2PMSOTGU3nJ4VOSo7aq3W6mR8tcRCgygd8fS-4Ra41oHPo3F3P=s900-c-k-c0x00ffffff-no-rj"

# Date Format for Discord Footer
# Options: "DD/MM/YYYY" or "MM/DD/YYYY"
dateFormat: "DD/MM/YYYY"

# Number of recent articles to check for updates.
# Default is 5. Minimum is 1.
checkLimit: 3

# Refresh Interval 
# Time in MINUTES (default: 120 = 2 hours)
# Examples: 
#   60  = 1 hour
#   1440 = 1 day
refreshInterval: 120

# News Types (Genres)
# Uncomment the categories you want to track.
# NOTE: By default, only 'latest' is enabled. To enable specific categories, remove the '#' at the start of the line.

genres:
  - latest

# === Other Categories (Uncomment to enable) ===
#  - announcements
#  - updates
#  - rockstar
#  - backward_compatibility
#  - circoloco_records
#  - content_updates
#  - contest
#  - creator_jobs
#  - crews
#  - crews_recruiting
#  - gameplay_clips
#  - events
#  - fan_art
#  - fan_videos
#  - game_tips
#  - music
#  - livestream
#  - rockstar_launcher
#  - sales
#  - twitch
#  - warehouse
#  - in_memoriam
#  - grand_theft_auto_the_trilogy
#  - grand_theft_auto_v
#  - grand_theft_auto_vi
#  - gta_online
#  - la_noire
#  - max_payne
#  - max_payne_3
#  - red_dead_online
#  - red_dead_redemption
#  - red_dead_redemption_2
